### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused',))

### ISSUE THREAD

**Issue by moFang222** [jiahuanluo/Federated-Benchmark#2]
运行sh ./run.sh street_5 5 yolo 1234时出现

![image](https://user-images.githubusercontent.com/25848511/77384370-33e4c300-6dc0-11ea-822e-3a1811097c66.png)
然后服务器端的日志文件信息为

![image](https://user-images.githubusercontent.com/25848511/77384405-44953900-6dc0-11ea-997b-e1e01ae4714f.png)
请问该怎么解决这个问题呢？

**Comment by moFang222** [comment]
I solved this by changing the ping_timeout to 3600
change
```
        self.socketio = SocketIO(self.app, ping_timeout=3600000,
                                 ping_interval=3600000,
                                 max_http_buffer_size=int(1e32))
```
To
```
        self.socketio = SocketIO(self.app, ping_timeout=3600,
                                 ping_interval=3600000,
                                 max_http_buffer_size=int(1e32))
```

**Comment by CodePothunter** [comment]
Well done. Thank you.
