### ISSUE TITLE
Hi, how to use this project with FATE?

### ISSUE THREAD

**Issue by ezekielqu** [jiahuanluo/Federated-Benchmark#4]
I'm new to this. I follow your instruction and find that when I run "run_server.sh street_5 yolo 1234", nothing seems happen. Can this project be used separately? Or it should be run in a FATE docker? I appreciate it if you can offer a more detailed guide.

**Comment by chenwanqq** [comment]
output is in experiements dir or nohup.out. You can modify run_server.sh manually to relocate log_dir.

**Comment by ezekielqu** [comment]
Thank you so much, I find that log file and try to understand how this project works.

**Comment by ezekielqu** [comment]
> output is in experiements dir or nohup.out. You can modify run_server.sh manually to relocate log_dir.

Thank you so much, I find that log file and try to understand how this project works.
